use_frameworks!

platform :tvos, '14.0'

target 'MediastreamPlatformSDKAppleTV_Example' do
  pod 'MediastreamPlatformSDKAppleTV', :path => '../'

  target 'MediastreamPlatformSDKAppleTV_Tests' do
    inherit! :search_paths

    
  end
end
